import pandas as pd
import json
import couchdb

pd.options.mode.chained_assignment = None  # for raw-dataframe manipulation

PERCENTAGES_VALUES = ["50", "55", "60", "65", "70", "75", "80", "85"]


def generate_json(county, form, a, b, d, n, w) -> dict:
    """
    Final database requieres specific object composition in certain JSON value.
    This JSON is composed by various data according to the context. The crop
    categories are fixed variables for WI case. A dict is returned, JSON is
    generated in preproccesing of the database

            Parameters:
                    county (string): County specific name
                    form (string): Form pattern
                    a (string): Crop type value for A category
                    b (string): Crop type value for B category
                    d (string): Crop type value for D category

            Returns:
                    as_json (dict): JSON-like value
    """
    north, west = fix_coords(n, w)
    as_json = {
        "_id": f"MN_{county.upper()}_RH_{form}_{north}_{west}_2022",
        "state": "MN",
        "aip": "RH",
        "form": f"{form}",
        "county": f"{county.upper()}",
        "township": f"{north}",
        "range": f"{west}",
        "crop_types": {
            "A": ["corn", "sugar beets", "sweet corn"],
            "B": ["soybeans"],
            "D": ["oats", "rye", "wheat", "sunflowers"]
        },
        "crops": {"A": f"{str(a)}", "B": f"{str(b)}", "D": f"{d}"},
    }
    return as_json


def fix_coords(n, w) -> list:
    """
    Setting coords value and checking their values

            Parameters:
                    n (string): Coord candidate
                    w (string): Coord candidate

            Returns:
                    (list): fixed coords value
    """
    candidate = n.split(' ')
    if candidate[0] == 'All':
        return ['OTHER', 'OTHER']
    else:
        return [n, w]


def generate_form(production_level, percentage) -> str:
    """
    A form consisted of PXX-XX patter is generated by a production level
    parameter and a given percentaje

            Parameters:
                    production_level (string): Given value from original data
                    percentage (string): Specific product value

            Returns:
                    form (string): Valid pattern for database integration
    """
    return f"P{production_level.replace('%', '')}-{percentage}"


def main() -> None: # 91840 docs
    # # dev db
    # couch = couchdb.Server('http://hailUser:hailpro1995@52.162.35.208:5984/')
    # db = couch["hpdb-dev"]
    # # test db
    # couchT = couchdb.Server('http://test-db-user:tst-db-194581@52.159.92.148:5984/')
    # dbt = couchT["hpdb-tst"]
    # # prod db
    # couchP = couchdb.Server('http://prod-db-user:prd-db-9185601@52.159.103.140:5984/')
    # dbp = couchP["hpdb-prd"]

    dataframe = pd.read_excel(r'D:\Capmation\AIP\Rainhail\Rainhail\MN\cleaned_data_mn.xlsx')
    print("NaNs o Nones: ", dataframe.isnull().values.any())
    print("Zeros: ", (dataframe == 0).sum())

    rows, _ = dataframe.shape
    jsons = []
    counter = 0
    for row in range(0, rows):
        county = str(dataframe.iloc[row]['County']).strip()#.replace(' ', '')
        n = dataframe.iloc[row]['N']
        w = dataframe.iloc[row]['W']
        production_level = dataframe.iloc[row]['Modifier'].strip()
        for index in range(0, len(PERCENTAGES_VALUES)):
            a = str(round(dataframe.iloc[row]['c' + str(index)], 2))
            b = str(round(dataframe.iloc[row]['s' + str(index)], 2))
            d = str(round(dataframe.iloc[row]['w' + str(index)], 2))
            percentage = PERCENTAGES_VALUES[index]
            form = generate_form(production_level, percentage)
            json_ = generate_json(county, form, a, b, d, n, w)
            print(counter,json_)
            # db.save(json_)
            jsons.append(json_)
            counter +=1
    output_values = json.dumps(jsons, indent=2)
    # generating file from proccessed data
    data = open('mn_rainhail.json', 'wt')
    data.write(output_values)
    data.close()


if __name__ == '__main__':
    main()